### ISSUE TITLE
*** stash smacking detected ***  - node crash

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC-Storyteller/query-builder-server#20]
Most likely caused by inserting queries that are too long, and therefore causing a memory overflow in the C function xenon_run_query. Meaning we should actually fix the memory usage properly in this function.

void xenon_run_query( const unsigned int query_id, const unsigned char* query)
{
    char cmd[100];
//    sprintf(cmd, "echo \"%d %s\" >> xenon.out", query_id, query);
//    system(cmd);
    sprintf(cmd, "curl --data \"id=%d&query=%s\" http://daemon:4567/submit", query_id, query);
    system(cmd);
}

**Comment by romulogoncalves** [comment]
The issue should now be solved by:
https://github.com/NLeSC-Storyteller/query-builder-server/pull/21
